---
title: "Lists - In Class Exercises"
author: "Quang Le"
date: "DATA 2401"

output: html_document

---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
single_card <- list(suit="Hearts", face="King", value=13)
print(single_card)

```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
second_list <- list(
  suits = c("Hearts", "Diamonds", "Clubs", "Spades"),
  faces = c("Ace", "2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Queen", "King"),
  values = 1:13
)
print(second_list)
```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")
Newlist$a <- Newlist$a + 1
print(Newlist)

```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will give all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")
b$a[-2]
b$a[b$a > 7]
print(b)
```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")
x$z <- "NewItem"
print(x)

```
